repo: 'columns-of-cards'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - google-fonts
  - box-sizing
  - body-margin-0
  - img-block-100

html:
  - path: 'index.html'
    outline: false
    has:
      - ['link[href*="Open+Sans"]', 'The Google Font, `Open Sans` is missing']
      - ['h3', 'An `<h3>` makes sense in this situation because this is part of a larger website']
      - 'h3'
      - 'section'
      - 'div'
      - ['a.btn.btn-small', 'Copy & paste the small button code from the “Button styles” assignment']
    search:
      - 'The Quest for Anderon'
      - 'Tabatha R. Barrett'
      - 'Dinosaur Knights'
      - 'Thomas S. Hedegaard'
      - 'The Black Dragon'
      - 'Hana Čejková'
      - 'Light Speed Laser Ships'
      - 'Felicity Orta Olivárez'

css:
  - path: 'css/main.css'
    has:
      - ['.btn']
      - ['.btn:hover']
      - ['.btn-small']
    search:
      - 'Open Sans'
      - 'display: flex'
      - 'flex-direction'
      - 'flex-grow'
      - 'width: 25%'
      - '#f2f2f2'
      - '#333'
      - '#e2e2e2'
      - '#ccc'
      - '#aaa'
      - '#999'

screenshots:
  - path: 'index.html'
    sizes: [1400]
